#!/usr/bin/env Rscript
# Validate drug-repurposing outputs generated by scripts/15_combined_drug_repurposing.R.

suppressMessages({
  library(data.table)
})

out <- "d:/OneDrive/Statistics/Metagenomics/data/geo_atopic_dermatitis_longitudinal/disease_signature/analysis"

require_file <- function(path) {
  if (!file.exists(path)) {
    stop(sprintf("Missing required output: %s", basename(path)), call. = FALSE)
  }
}

require_cols <- function(dt, cols, label) {
  missing <- setdiff(cols, names(dt))
  if (length(missing) > 0) {
    stop(sprintf("%s is missing columns: %s", label, paste(missing, collapse = ", ")),
         call. = FALSE)
  }
}

drug_path <- file.path(out, "drug_repurposing_results.csv")
drug_anno_path <- file.path(out, "drug_repurposing_druggability_annotation.csv")
cmap_path <- file.path(out, "drug_repurposing_signature_reversal.csv")
summary_path <- file.path(out, "drug_repurposing_summary.csv")

invisible(lapply(c(drug_path, drug_anno_path, cmap_path, summary_path), require_file))

drug <- fread(drug_path)
drug_anno <- fread(drug_anno_path)
cmap <- fread(cmap_path)
summary <- fread(summary_path)

require_cols(
  drug,
  c("gene", "axis", "drug", "category", "stage", "druggability_tier",
    "open_targets_tractability", "dgidb_interaction_count", "dgidb_sources",
    "target_axis"),
  "drug_repurposing_results.csv"
)

require_cols(
  drug_anno,
  c("gene", "target_axis", "druggability_tier", "open_targets_tractability",
    "open_targets_known_drug_count", "dgidb_interaction_count", "dgidb_sources",
    "curated_drug_count"),
  "drug_repurposing_druggability_annotation.csv"
)

require_cols(
  cmap,
  c("query_axis", "perturbagen", "score", "rank", "known_ad_drug",
    "validation_hit", "method_status"),
  "drug_repurposing_signature_reversal.csv"
)

require_cols(
  summary,
  c("analysis_tier", "n_rows", "n_validation_hits", "method_status"),
  "drug_repurposing_summary.csv"
)

if (!any(drug_anno$target_axis == "AD_and_LS")) {
  stop("Expected at least one AD_and_LS druggability annotation row", call. = FALSE)
}

if (!any(cmap$known_ad_drug, na.rm = TRUE)) {
  stop("Expected known AD drug controls in signature-reversal output", call. = FALSE)
}

if (sum(cmap$validation_hit, na.rm = TRUE) < 1) {
  stop("Expected at least one recovered known AD drug validation hit", call. = FALSE)
}

cat("Drug-repurposing output validation passed.\n")
